### PR TITLE
158423572 Add passenger/user sign-up page

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Add websites's passenger sign-up page with a user registration form

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a webbrowser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-passenger-signup-158423572.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `passenger_signup.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-passenger-signup-158423572`

* Run `cd Ride-My-Way/UI/`

* Open `passenger_signup.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423572](https://www.pivotaltracker.com/story/show/158423572)

#### Screenshots 
screenshot from 2018-06-19 11-51-11
screenshot from 2018-06-19 11-49-55

### CODE REVIEW

**Comment by LWanjiru** [comment]
What inspired your UI? @artorious

**Comment by TheSteelGuy** [comment]
nice

**Comment by artorious** [comment]
Hi, @LWanjiru,
On a TED talk about design in general (can't remember the speaker), something they said stuck with me. "Never let aesthetic design get in the way of functionality" 

With this in mind, I am looking to develop a webapp that achieves the following; 

* Fits on a variety of screens
* lightweight and loads fast
* Looks or opens the same on different devices and browsers
* Simple to use and is legible (Straightforward)

**Comment by artorious** [comment]
@TheSteelGuy  and @LWanjiru  Thank you for taking time off your project to look at my work.

**Pull request merged**
