### PR TITLE
#158423572 update passenger signup form

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Removes unnecessary text from the header
* Changes navigation menu to buttons 
* Removes unnecessary input fields

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-passenger-signup-upd8-158423572.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `passenger_signup.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-passenger-signup-upd8-158423572`

* Run `cd Ride-My-Way/UI/`

* Open `passenger_signup.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423572](https://www.pivotaltracker.com/story/show/158423572)

#### Screenshots 
reguser

#### Questions:

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
screenshot
Please confirm whether the first sentence is correct.

**Comment by artorious** [comment]
Good looking out @meshack-mbuvi

**Comment by LWanjiru** [comment]
Would you consider having the sign in buttons in the Navigation bar? Also, from this PR ==> https://github.com/artorious/Ride-My-Way/pull/14 it feels like there is a redundancy in having separate sign-in pages for your users. How about having one sign-in form that then affords you the relevant fields to fill depending on whether you are a driver or not?

**Comment by artorious** [comment]
@LWanjiru I will improve the navigation bar and refactor the sign-in pages to have one comprehensive page that serves both users.

**Comment by artorious** [comment]
@LWanjiru I've made changes, kindly advise.

**Comment by LWanjiru** [comment]
FIx conflicts

**Review by LWanjiru — APPROVED** [review]
Looks good

**Pull request merged**
