### PR TITLE
#158423840 Update  driver profile 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Updates driver profile page
* Adds User Account  information 

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-driver-profile-upd8-158423840.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `driver_profile.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-driver-profile-upd8-158423840`

* Run `cd Ride-My-Way/UI/`

* Open `driver_profile.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423840](https://www.pivotaltracker.com/story/show/158423840)

#### Screenshots 
driver profile

#### Questions:

### CODE REVIEW

**Comment by Ogollah** [comment]
Nice ui.

**Comment by meshack-mbuvi** [comment]
Font-size for the bio too small if am not wrong.Am struggling to read.

**Comment by Quantum-35** [comment]
Looks good to me but you have to check on your fonts and also my LFA told me its not a lorem ipsum is used for templating you should write something readable

**Review by JoshuaOndieki — APPROVED** [review]
Looks great and responsive :+1: :sparkles: 
However, for the rating, I would prefer the empty stars to be grey.

**Comment by xcixor** [comment]
Great UI and nice flow of thought. All necessary features incorporated, awesome.

**Comment by kwameasiago** [comment]
I like how  you have displayed the icons for the likes and messages

**Comment by artorious** [comment]
@Ogollah @meshack-mbuvi @Quantum-35 @xcixor @SelaDanti Thank you for taking time to review. I've made the recommended changes.

**Comment by LWanjiru** [comment]
I am curious about the `D.O.B` and `Email` details, are they really important to the user?

**Comment by LWanjiru** [comment]
Can be merged.

**Comment by artorious** [comment]
@LWanjiru I've removed the unnecessary `DOB` and `email` information

**Pull request merged**
