### PR TITLE
#158423840  Add drivers profile page

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

Adds drivers' profile page which holds;
 
* All details about driver. 
* Active/open rides 
* Contact numbers for active passengers
* Passenger log (history)

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a webbrowser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-driver-profile-158423840.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `driver_profile.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-driver-profile-158423840`

* Run `cd Ride-My-Way/UI/`

* Open `driver_profile.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423840](https://www.pivotaltracker.com/story/show/158423840)

#### Screenshots 
driverprof

#### Questions:

### CODE REVIEW

**Comment by evamaina** [comment]
Nice PR

**Comment by artorious** [comment]
Thank you @evamaina  for taking the time to review my project

**Review by LWanjiru — APPROVED** [review]
@artorious Consider more consistency with the background colours, there is a lot going on in terms of contrast and the design itself that makes it a bit strenuous to the eyes. I believe you have a great colour combination, it just needs an improvement on how you organize the page. 

All else looks good.

**Comment by artorious** [comment]
@evamaina @LWanjiru Thanks for the input. Changes below.
drvprof

**Pull request merged**
