### PR TITLE
#158423600 update home/index page

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Adds a description of the application and how it works 

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-index-signin-upd8-158423600.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `index.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-index-signin-upd8-158423600`

* Run `cd Ride-My-Way/UI/`

* Open `index.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423600](https://www.pivotaltracker.com/story/show/158423600)

#### Screenshots 
signuppoa

#### Questions:

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
I think you should choose a color which is not so black as such for the header. Also, consider having white text on black background. You can look a coolers.co for various color combinations.

**Comment by artorious** [comment]
@meshack-mbuvi Thanks for you're input. 
Is it a readability issue or the black/sky blue combination that does not look appealing? kindly `color`
I had tried White on black...... for me feels a bit bland.

**Review by JoshuaOndieki — APPROVED** [review]
Looks great :+1: 
Personally, I would have set the header background to 
 Gray20 >> #333 or Matte Black >> #141414
This is not a change request as it's just personal preference and only makes very minor changes to the UI.

**Comment by artorious** [comment]
@meshack-mbuvi @JoshuaOndieki  you reviews are very welcome and appreciated. @JoshuaOndieki, from experience, matte has a low contrast and color vibrancy, especially on low-resolution devices. I'm actually a big fan of matte.

**Comment by LWanjiru** [comment]
Hey @artorious do you remember what we discussed regarding your navigation bars? I feel that has not been addressed in this implementation.  Remember, the key to a good UI is the usefulness of information provided, also, do you need 2 navigation bars? Is there a better way to implement how the logo is displayed on the page?

**Comment by artorious** [comment]
Hi, @LWanjiru  Thank you for the review. I will improve the design on the navigation bar and remove the redundancies that I forgot to take out on the previous feedback implementation. I will also center the logo on the screen.

**Comment by artorious** [comment]
@LWanjiru I've made changes, kindly advise.

**Comment by LWanjiru** [comment]
Fix the conflicts

**Review by LWanjiru — APPROVED** [review]
Looks good.

**Pull request merged**
