### PR TITLE
#158423631 Add drivers landing page 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Add websites's drivers' landing page. A driver should able to see all currently open rides by other drives and should have access to a feature that enables him/her to add new post offers (button) 

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a webbrowser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-driver-signin-158423631.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `drivers_landing.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-drivers-landing-page-158423631`

* Run `cd Ride-My-Way/UI/`

* Open `drivers_landing.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423631](https://www.pivotaltracker.com/story/show/158423631)

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
looks awesome, I like the details.

**Comment by TheSteelGuy** [comment]
detailed pr kudos. The pages are also awesome.

**Comment by Ogollah** [comment]
Looks great.

**Comment by Xerrex** [comment]
I like the responsive page design. Try to not show the ride ID on the page.

**Comment by artorious** [comment]
Thanks for taking the time. @meshack-mbuvi  @TheSteelGuy @Ogollah and @Xerrex .

@Xerrex, please `color` - `Try to not show the ride ID on the page.`

**Review by LWanjiru — COMMENTED** [review]
refer below

**Review by LWanjiru — APPROVED** [review]
Good eye for design, also I like that your PR provides options to different users on how to test the feature. I hope your `README.md` will also mirror this trend. Remember to `Add a new line` at the end of your files.  Also, I hope you are extending this eye for design to your teammates even as you review each others PRs

**Comment by artorious** [comment]
@LWanjiru  I will strictly observe `\n` at `EOF`. 
I've looked it up and now I know why the command prompt sometimes displays on the same line as a script's output.

**Pull request merged**
