### PR TITLE
#158423707 Update the manage ride page

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Updates the driver's view of an expanded ride request.
* Removess unnecessary text on the header and ride details sections

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-drivers-ride-expanded-upd8-158423707.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `expanded_ride_driver.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-drivers-ride-expanded-upd8-158423707`

* Run `cd Ride-My-Way/UI/`

* Open `expanded_ride_driver.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423707](https://www.pivotaltracker.com/story/show/158423707)

#### Screenshots 
manage

#### Questions:

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
This is awesome. I like that you are indicating number of reservations per user. I am thinking that this information should be shared when the driver and passenger get in touch.

**Review by JoshuaOndieki — APPROVED** [review]

**Comment by artorious** [comment]
Hi @meshack-mbuvi and @JoshuaOndieki, Thanks for your input on this. Although I don't know how to implement it yet, I was envisioning automated tracking of seat capacity. As a user, I would personally love to have the process automated. But yes,  you make a valid point, It feels like I'm taking away the users' conversation pieces,  But don't you think that it's easier when you have a head's up on a conversation you are about to have? (even in our day-to-day?) 

I've made a few tweaks to the UI .

**Comment by LWanjiru** [comment]
I love the implementation, it ensures that when a car is fully booked, a passenger can go look for another ride without having to call the car driver to find out. Also, the driver can refuse to pick a ride is the number of user-indicated passengers is more than his capacity allows. Great stuff! I am not so sure about the `cost` considering our discussion last Friday, but I am very interested in seeing how you implement it.

Can be merged

**Comment by artorious** [comment]
@LWanjiru I had envisioned having the `cost` field as an optional field for the driver when he's offering a ride. The passenger only sees that information if the driver had specified a cash value.

**Pull request merged**
