### PR TITLE
#158423631 updates drivers landing page 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Updates drivers landing page by reformating table to hold current/open ride
* Adds a page for closed rides (history/log)
* Adds page to create a new ride offer

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-drivers-landing-upd8-158423631.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `drivers_landing.html` on a browser
* in the `UI` folder, open `new_ride.html` on a browser
* in the `UI` folder, open `drivers_history.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-drivers-landing-upd8-158423631`

* Run `cd Ride-My-Way/UI/`

* Open `drivers_landing.html` on a browser
* Open`new_ride.html` on a browser
* Open `drivers_ride_history.html`on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423631](https://www.pivotaltracker.com/story/show/158423631)

#### Screenshots 
newoffer
historydriver
drivers landing page

#### Questions:

### CODE REVIEW

**Comment by xcixor** [comment]
The layout looks great and the UI is self explanatory and easy to use. If I may suggest you can also include a field for the vehicles registration number so that the passenger can have an idea of the car that will be carrying them

**Comment by meshack-mbuvi** [comment]
@xcixor  Does having car's registration number give a passenger an idea of the car? Just curous

**Comment by artorious** [comment]
@xcixor thanks for bringing that to my attention. @meshack-mbuvi have you forgotten that it's a  Kenyan trait to ask about registration number intead of the condition. @xcixor  is right on the money. Thanks, guys. I've added a field in driver registration, the vehicle description will be seen by a passenger during a search.

**Comment by meshack-mbuvi** [comment]
Suupose the product will be used in United states.

**Comment by artorious** [comment]
@meshack-mbuvi @xcixor. Point well taken, We cannot be thinking locally if we expect our work to reach out beyond our environment. I was making fun of myself for having been amongst the many Kenyans who've done that. 

Kindly offer  feedback on changes

**Comment by LWanjiru** [comment]
@meshack-mbuvi I am curious about your comment `The product will be used in United States`. What is the background information on this?

**Comment by LWanjiru** [comment]
@artorious Definitely looks better, still, a few loose ends when it comes to capturing the end user needs but I have a feeling it will become clearer as you build the API. Can be merged.

**Comment by meshack-mbuvi** [comment]
@LWanjiru I wanted to make him think outside the box

**Pull request merged**
