### PR TITLE
#158423600 Add index (passenger sign-in) page 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Add websites's index page with a user sign up form

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a webbrowser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-index-signin-page-158423600.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `index.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-index-signin-page-158423600`

* Run `cd Ride-My-Way/UI/`

* Open `index.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423600](https://www.pivotaltracker.com/story/show/158423600)

#### Screenshots 
screenshot from 2018-06-19 05-41-15
screenshot from 2018-06-19 05-39-46

#### Questions:

### CODE REVIEW

**Comment by kwameasiago** [comment]
i like how responsive it is

**Comment by JoshuaOndieki** [comment]
Great work on the responsiveness 👏
Would it be better to have a universal login and maybe signup? I suggest this to reduce the workload needed when refactoring your layouts

**Comment by xcixor** [comment]
Great work on the responsiveness, but if i may, maybe you can try to have the font contrast more clearly with the background

**Comment by Xerrex** [comment]
looks good. But reduce the banner height.

**Comment by artorious** [comment]
Hello @SelaDanti , @JoshuaOndieki @xcixor and @Xerrex ,
Thank you for your input. Much appreciated.
I'm working to implement

**Pull request merged**
