### PR TITLE
#158518449 refactor passenger profile update page

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Display current user details  
* Display for that prompts the user to update their details

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-passenger-profile-update-upd8-158518449.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `update_passenger_profile.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-passenger-profile-update-upd8-158518449`

* Run `cd Ride-My-Way/UI/`

* Open `update_passenger_profile.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158518449](https://www.pivotaltracker.com/story/show/158518449)

#### Screenshots 
update_pass

#### Questions:

### CODE REVIEW

**Comment by Ogollah** [comment]
Looks good.

**Comment by JoshuaOndieki** [comment]
Just wondering, do you really want to merge with master?

**Comment by artorious** [comment]
Good-looking-out @Ogollah and @JoshuaOndieki . Appreciated.

**Comment by LWanjiru** [comment]
Good work! Can be merged

**Pull request merged**
