### PR TITLE
#158423577 Update driver's registration

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Removes unnecessary text from the header
* Changes navigation menu to buttons 
* Removes unnecessary input fields

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-driver-signup-upd8-158423577.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `driver_sign_up.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-driver-signup-upd8-158423577`

* Run `cd Ride-My-Way/UI/`

* Open `driver_sign_up.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423577](https://www.pivotaltracker.com/story/show/158423577)

#### Screenshots 
driversignup

#### Questions:

### CODE REVIEW

**Comment by Ogollah** [comment]
This looks nice.

**Comment by TheSteelGuy** [comment]
nice one

**Comment by meshack-mbuvi** [comment]
It looks good

**Comment by LWanjiru** [comment]
Major improvement on how the UI looks. Consider improving the navigation bar ... Can be merged

**Comment by artorious** [comment]
@LWanjiru I will make improvements on the navigation bar. Thank you or the feedback.

**Pull request merged**
