### PR TITLE
#158423645 Update expanded ride offer

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Adds passenger's view of an exapnded ride offer which can be requested

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-passengers-expandedride-upd8-158423645.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `expanded_ride_passenger.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-passengers-expandedride-upd8-158423645`

* Run `cd Ride-My-Way/UI/`

* Open `expanded_ride_passenger.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423645](https://www.pivotaltracker.com/story/show/158423645)

#### Screenshots 
search_criteria

#### Questions:

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
In your ride offer, I think you should combine date and time to be in the same field

**Review by JoshuaOndieki — CHANGES_REQUESTED** [review]
Checking the **UX** I feel like it's tedious for users to look on the left for a field label and then roll their eyes to the right to see the data that's labeled.
You could put the label and data texts closer maybe with text-align.
A user should be able to look on the screen and understand all data without eye rolling to check labels

**Review by JoshuaOndieki — APPROVED** [review]

**Comment by LWanjiru** [comment]
What does the `Detours` field entail exactly?
Also, really look into improving the navigation bar, there is a lot going on here. However, these are adjustments that will come in later. Can be merged

**Comment by artorious** [comment]
@LWanjiru I will improve the UI description for `detours` to avoid ambiguity. Thank you.

**Pull request merged**
